[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
application = "5BMcPrhViYHQ9fgPofiPGNE1aawt8g8Jb8txrBRGAFu2"
messenger = "3m3V6iGoTzRAcw52mtpmbUEzqzqpm9XSvYrczsWjiMTx"
solagram = "7W7K9yAshEJBgPRNPW1fDiXuVDzjKBPcBWCC6UGrWxKC"
token = "4kmeDwmjEiVaGHSD3CFgYukd3nSt4eNNBwJ2eEdb2sqK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
generate-clients = "yarn ts-node ./scripts/generate-clients.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
