name: Tests

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Setup Anchor
      uses: metadaoproject/setup-anchor@v3.3
      with:
        anchor-version: '0.30.1'
        solana-cli-version: '2.2.20'
        node-version: '22.5.1'

    - name: Check versions
      run: |
        rustc -V
        anchor -V
        solana -V
        node -v
      shell: bash

    - name: Setup Yarn
      run: npm i -g yarn

    - name: Install Yarn dependencies
      run: yarn install --frozen-lockfile --prefer-offline

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          node_modules
          ~/.cache/yarn
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock', '**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Setup Solana test environment
      run: |
        solana config set --url localhost
        solana-keygen new --no-passphrase --force

    - name: Generate codama clients
      run: anchor run generate-clients

    - name: Run tests
      run: anchor test
